### ISSUE TITLE
No value for handduk?

### ISSUE THREAD

**Issue by dpriskorn** [dpriskorn/LexSAOB#6]
I today changed the script to add SAOB->no-value for all lexemes that do not have an own entry in SAOB.
SAOB contains about 116.000 entries and about 500.000 lookup words.
Because the entries have many of our lexemes in one entry it is unclear how to best model this.

I decided today without communicating with the community first (bummer perhaps) add no-value to the lexemes that do not have an entry. 

It is fully possible to later on add "described by source"->SAOB and the id in the reference to the rest of our lexemes that actually do appear in the dictionary.

Currently the organization Svenska Akademin does not collaborate with us, so we have to query their HTTP-webpage for every single lexeme we want to check if it appears anywhere in the dictionary. This is expensive for their server.

For that reason it is nice to easily generate a list of lexemes that do not have a SAOB-entry-id and look them up. Adding no-value helps with that because we can list all swedish lexemes with SAOB-no-value in WDQS :)

**Comment by salgo60** [comment]
Didnt you find an API?

**Comment by dpriskorn** [comment]
Yep, I worked hard on supporting it yesterday and it now works :D
https://github.com/dpriskorn/LexSAOB/blob/ea3b8403eb4ba88ff6885664231631d9e6515d11/models/saob.py#L12
Only thing needed now is to create a proposal "SAOB section ID"
Unfortunately the seek parameter is needed, so the ID becomes: 
e.g. "arbetsplats#U_A1959_186919"
https://www.saob.se/artikel/?seek=arbetsplats#U_A1959_186919
Formatter URL is
https://www.saob.se/artikel/?seek=$1

**Comment by dpriskorn** [comment]
Done https://www.wikidata.org/wiki/Wikidata:Property_proposal/Svenska_Akademins_Ordbok-section_ID#Motivation
I'll continue adding no-value statements now, so we can easily query and find the subentrys based on that.
